spring:
  application:
    name: mybatis-crypto-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql_crypto?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

server:
  port: 8888

mybatis:
  type-aliases-package: com.mybatis.crypto.entity


mybatis-crypto:
  fail-fast: true
  default-key: 8888
  default-encryptor: io.github.whitedg.mybatis.crypto.BasicTextEncryptor

